# Generated by Django 5.0.1 on 2024-03-03 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
